// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE9HMWtZXJj2ww6MAaai5GJA4bFXHnJ60',
    appId: '1:164114031277:web:4b1482589dc4dbec8f9c24',
    messagingSenderId: '164114031277',
    projectId: 'permit-pro-v01',
    authDomain: 'permit-pro-v01.firebaseapp.com',
    storageBucket: 'permit-pro-v01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARs_68oClvMIPxLO8R8PXq8EUOYTQmYMM',
    appId: '1:164114031277:android:1b4aa5d1def684458f9c24',
    messagingSenderId: '164114031277',
    projectId: 'permit-pro-v01',
    storageBucket: 'permit-pro-v01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAPgz7YXng_10LETfN8e5Mfxs53tPmPz4',
    appId: '1:164114031277:ios:333164554a4933738f9c24',
    messagingSenderId: '164114031277',
    projectId: 'permit-pro-v01',
    storageBucket: 'permit-pro-v01.firebasestorage.app',
    iosBundleId: 'com.example.permitpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAPgz7YXng_10LETfN8e5Mfxs53tPmPz4',
    appId: '1:164114031277:ios:333164554a4933738f9c24',
    messagingSenderId: '164114031277',
    projectId: 'permit-pro-v01',
    storageBucket: 'permit-pro-v01.firebasestorage.app',
    iosBundleId: 'com.example.permitpro',
  );
}
